version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: seguros-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: seguro
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - "./scripts.sql:/docker-entrypoint-initdb.d/1.sql"