# Use a imagem oficial do MySQL
FROM mysql:latest

# Defina as variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=seguros
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=1234

# Copie o script SQL para inicializar o banco de dados
COPY ./scripts.sql /docker-entrypoint-initdb.d/

# Exponha a porta padrão do MySQL
EXPOSE 3306
